'project_id_env': 'CROWDIN_PROJECT_ID'
'api_token_env': 'CROWDIN_PERSONAL_TOKEN'
'base_path': '.'
'base_url': 'https://api.crowdin.com'

# Flatten files in Crowdin
'preserve_hierarchy': false

# "Source" files, which are .POT files extracted from the source code.
# The built files are .PO files that are the compiled by `compile-translations`
# script in `scripts`.
files:
  [
    {
      'source': '.translations/en/reviewed-extensions-messages.pot',
      'translation': '.translations/%locale_with_underscore%/reviewed-extensions-messages.po',
    },
  ]
