name: 🐛Bug report
description: Create a bug report about an extension
title: '[Extension name] <title>'
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ If the bug is related to GDevelop itself, go to [GDevelop Github Issues](https://github.com/4ian/GDevelop/issues)
        ⚠️ Thank you for taking the time and effort to report an issue!
        ⚠️ Please edit and complete this form before submitting:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)
        required: true
  - type: input
    attributes:
      label: Enter the name of the extension
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug of the extension
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        * Please include a link to a game if possible!
        * If applicable, add screenshots to help explain your problem.
      placeholder: |
        1. Go to '...'
        2. Use action '...'
        3. Launch the game
        4. See it's not working properly
    validations:
      required: true
  - type: dropdown
    attributes:
      label: GDevelop platform
      description: Which platform of GDevelop are you using?
      multiple: true
      options:
        - Desktop
        - Web
        - Mobile
    validations:
      required: true
  - type: input
    attributes:
      label: GDevelop version
      description: |
        Which version of GDevelop are you using?
        Take a look here: [Editor Home - About GDevelop - "This version of GDevelop is: ~~~"]
      placeholder: 5.1.159? 5.1.160?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Platform info
      value: |
        <details>

        *OS (e.g. Windows, Linux, macOS, Android, iOS)*
        >

        *OS Version (e.g. Windows 10, macOS 10.15)*
        >

        *Browser(For Web) (e.g. Chrome, Firefox, Safari)*
        >

        *Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
        >

        </details>
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
