blank_issues_enabled: false
contact_links:
  - name: GDevelop Discord
    url: https://discord.gg/gdevelop
    about: Discuss on the forum or on the Discord to get help with an extension.
  - name: GDevelop Forums
    url: https://forum.gdevelop.io
    about: You can also discuss a new feature request on the forum.
  - name: GDevelop Extensions Trello
    url: https://trello.com/b/AftjL2v1/gdevelop-extensions
    about: See this dashboard with extension ideas and extensions being worked on by the community.
