name: 🔄Extension update
description: Submit an extension update
title: 'Extension update: <title>'
labels: [🔄 Extension update]
body:
  - type: markdown
    attributes:
      value: '# Extension update submission'
  - type: textarea
    id: description
    attributes:
      label: Changes
      description: Describe the features you added or the bugs you fixed.
      placeholder: This update adds...
  - type: textarea
    id: how-to
    attributes:
      label: How to use the new features
      description: Describe how your new features can be used.
      placeholder: If you put behavior X on a sprite, you can make a...
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you have done all of this before submitting!
      options:
        - label: "I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices)."
          required: true
        - label: I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
          required: true
        - label: I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example file
      description: Please drag and drop an example project using your extension, compressed in a ZIP file, into this text field. **DO NOT PUT A LINK TO AN EXTERNAL SERVICE LIKE GOOGLE DRIVE!**
      placeholder: '[MyExample.zip]()'
    validations:
      required: true
  - type: textarea
    id: extension
    attributes:
      label: Extension file
      description: Please drag and drop your extension JSON file, compressed in a ZIP file, into this text field. **DO NOT PUT A LINK TO AN EXTERNAL SERVICE LIKE GOOGLE DRIVE!**
      placeholder: '[MyExtension.json.zip]()'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You also may have to create an account on GitHub before posting.
        Your extension will be added to the list after we have checked that it contains no virus and respects the best practices.
        Thanks for contributing to GDevelop! 🙌
