name: New extension
description: Submit your extension to be integrated in the list of community extensions
title: 'New extension: <title>'
labels: [✨ New extension]
body:
  - type: markdown
    attributes:
      value: "# Extension submission"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what your extension does here.
      placeholder: This extension adds...
  - type: textarea
    id: how-to
    attributes:
      label: How to use the extension
      description: Describe how your extension can be used.
      placeholder: This extension can be useful to...
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you have done all of this before submitting!
      options:
        - label: "I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices)."
          required: true
        - label: I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Please upload an example project using your extension.
      placeholder: https://example.com/myExample.zip
    validations:
      required: true
  - type: textarea
    id: extension
    attributes:
      label: Extension file
      description: Please upload your extension JSON file.
      placeholder: https://example.com/myExtension.json
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You also may have to create an account on GitHub before posting.
        If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
        Thanks 🙌
