name: New extension
description: Submit your extension to be integrated in the list of community extensions
title: 'New extension: <title>'
labels: [✨ New extension]
body:
  - type: markdown
    attributes:
      value: "# Extension submission"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your extension and how it can be used!
      placeholder: This extension adds...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you have done all of this before submitting!
      options:
        - label: "Extension has a proper name and description (For example, Name: xxx, Description: yyy)."
          required: true
        - label: Extension has tags (for example "platform, brick, breakable").
          required: true
        - label: All behaviors have a description (for example "Makes the object move according to the users keystrokes").
          required: true
        - label: All functions (actions, conditions, expressions) have descriptions and proper sentences.
          required: true
        - label: I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices.
          required: true
        - label: I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
          required: true
  - type: input
    id: example
    attributes:
      label: Example
      description: Please enter a link to an example project using your extension.
      placeholder: https://example.com/myExample.zip
    validations:
      required: true
  - type: input
    id: extension
    attributes:
      label: Extension file
      description: Please enter a link to your extension JSON file.
      placeholder: https://example.com/myExtension.json
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You also may have to create an account on GitHub before posting.
        If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
        Thanks 🙌
