name: Automatic addition of PRs to the pending reviews list
on:
  pull_request:
    types: [opened, labeled]
jobs:
  assign-project:
    name: Add card to pending review
    if: ${{ contains(github.event.pull_request.labels.*.name, '✨ New extension') || contains(github.event.pull_request.labels.*.name, '🔄 Extension update') }}
    runs-on: ubuntu-latest
    steps:
      - name: Add card to pending review
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Extensions review
          column-name: Needs review
          issue-number: ${{ github.event.number }}
