name: GDevelop Extensions Issues automatic workflow
on: [issues]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues about adding a new extension without providing anything
      uses: arkon/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        type: "body"
        regex: ".*Finally, attach the .json file of your extension here.*"
        message: "Hi @${issue.user.login}! 👋 This issue was automatically closed because it seems that you have not included any file.\n\nGitHub is a place for the technical development of GDevelop itself - you may want to go on the [forum](https://forum.gdevelop-app.com/), the Discord chat or [read the documentation](http://wiki.compilgames.net/doku.php/gdevelop5/start) to learn more about GDevelop. Thanks!"
    - name: Autoclose issues about adding a bug without changing the bug report template
      uses: arkon/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        type: "body"
        regex: ".*Use action '\\.\\.\\.\\.'.*"
        message: "Hi @${issue.user.login}! 👋 This issue was automatically closed because it seems that you have not included any steps to reproduce the bug.\n\nGitHub is a place for the technical development of GDevelop itself - you may want to go on the [forum](https://forum.gdevelop-app.com/), the Discord chat or [read the documentation](http://wiki.compilgames.net/doku.php/gdevelop5/start) to learn more about GDevelop. Thanks!"